### ISSUE TITLE
Allow users of the client code to be notified when low-level data is read

### ISSUE THREAD

**Issue by glasser** [faye/faye-websocket-node#35]
In our application, we have some heartbeat-style timeouts that let us detect the case where we haven't heard anything from the server in a long time.  (We implement this using application-level heartbeats in normal data frames, though the same issue would apply if we used WebSocket ping/pongs.)

Users behind very slow connections end up unnecessarily triggering these timeouts if the "pong" response is stuck behind a bunch of other messages or a single long message, though.

In the "large number of small messages" case, we can solve this by just considering any received message to effectively be a "pong".  But this doesn't work for the "single large message" case, because the Websocket API doesn't give us any way of knowing that we've received some data over the network until a full message arrives.

Some non-ideal solutions:
- Manually split up our large messages into small messages at the app level. This reduces to another guessing game about how big is "too big" and is a burden on app code authors.
- Implement message fragmenting for Faye on our server, and add some sort of "message fragment received" event to Faye client. This is arguably more work than the solution I'm going to propose and still requires guessing game about good sizes.  Note that the fact that you can intersperse PONG frames between fragments is a red herring here, since the server will presumably still put all of the fragments onto the wire at once.
- Switch from faye-websocket to websocket-driver and reimplement all of faye-websocket's features in order to add one tiny feature.  I did this before for proxy support and it was pretty unpleasant to try to get all the error handling right... turns out that faye-websocket is in fact some pretty good and useful code!
- Reach inside the websocket object to get at `_stream` and place an event handler (for 'readable' or 'data') there (or stream it somewhere).  Obviously icky due to looking at internal fields.

I think what I'm looking for is the ability to just add a "dataReceived" or something handler on the websocket object directly, and get it invoked (not necessarily with any data) whenever `_stream` receives any bytes.  I'm happy to implement this myself if you let me know what you think would make a good API.

(There's some trickiness around the special handling of "on 'data'" in Node where just adding that listener has side effects... and "on 'readable'" doesn't support 0.8.)

**Comment by jcoglan** [comment]
For the server side of a socket, you already have access to the TCP stream because you need that to instantiate the WebSocket, i.e.:

```js
server.on('upgrade', function(request, socket, body) {
  body.on('data', function() { /* ... */ });
  var ws = new WebSocket(request, socket, body);
});
```

As for the client, I would just listen to `ws._stream`. Given that `ws` itself is already a duplex stream I can't see a clean way to add a TCP-level listener that doesn't look like just as much of a hack as that does.
