### ISSUE TITLE
need unpipe

### ISSUE THREAD

**Issue by cades** [faye/faye-websocket-node#40]
Hi faye, thanks for creating this awesome tool!
I encounter a problem that once ws was piped to another stream, I can undo it with `ws.unpipe()`
Are there any method I didn't know, or this is a missing feature?

**Comment by jcoglan** [comment]
This module and `websocket-driver` use old-style streams since they were written for compatibility with pre-0.10 versions of Node. You might be able to get `unpipe` by wrapping the streams using http://nodejs.org/api/stream.html#stream_readable_wrap_stream.

**Comment by cades** [comment]
@jcoglan thanks A LOT!!
Now it works like a charm :)
