### ISSUE TITLE
Can send duplicate close frames

### ISSUE THREAD

**Issue by glasser** [faye/faye-websocket-node#41]
When using Chrome as  client talking to a Faye server, after a normal close, Chrome shows in its network inspector (after the `c[1000,"Normal closure"]` frame) a frame which it displays as `(Opcode -1)`.  

I am running `faye-websocket` 0.9.3, `websocket-driver` 0.5.3, and `websocket-extensions` 0.1.1. I do not have permessage-deflate or any other etension enabled.

This did not occur in the previous version of Meteor, where I used faye-websocket 0.8.1 with websocket-driver 0.4.0.

I will try to demonstrate an actual reproduction shortly.

**Comment by glasser** [comment]
(BTW, if the thing about `c[1000` above was confusing... that's a SockJS thing.)

OK, playing around with Wireshark for a moment, the issue isn't actually sending -1: it's sending a second server-client CLOSE frame.

I applied this diff to faye-websocket-node:
```
diff --git a/examples/server.js b/examples/server.js
index 6e5abf1..c4f53ce 100644
--- a/examples/server.js
+++ b/examples/server.js
@@ -6,13 +6,17 @@ var WebSocket = require('../lib/faye/websocket'),
 
 var port    = process.argv[2] || 7000,
     secure  = process.argv[3] === 'tls',
-    options = {extensions: [deflate], ping: 5};
+    options = {extensions: [], ping: 5};
 
 var upgradeHandler = function(request, socket, head) {
   var ws = new WebSocket(request, socket, head, ['irc', 'xmpp'], options);
   console.log('[open]', ws.url, ws.version, ws.protocol, request.headers);
 
-  ws.pipe(ws);
+  ws.on('message', function (event) {
+    console.log("GOT MESSAGE", event.data);
+    ws.send("Reply");
+    ws.close();
+  });
 
   ws.onclose = function(event) {
     console.log('[close]', event.code, event.reason);
```

Going to http://localhost:7878/ws.html in Chrome (wireshark didn't want to consider port 7000 as HTTP/Websocket) and looking in Wireshark, I saw server -> client close, client -> server close, then a second server -> client close.

**Comment by jcoglan** [comment]
This ought to be fixed by https://github.com/faye/websocket-driver-node/commit/8a0235ef517e04d0ad02fa12a96689516c27daae.
