### ISSUE TITLE
Cannot find TypeDefined at typings.

### ISSUE THREAD

**Issue by livingyang** [faye/faye-websocket-node#57]
I use typescript for my project. Any plans to add typings definition?

**Comment by jcoglan** [comment]
I don't have any plans to add TypeScript support, mainly because I don't use TypeScript and have no experience with it, so such code will not be well maintained. Is there a way for downstream package maintainers to add this information?

**Comment by jcoglan** [comment]
I'm going to close this since I have no plans to implement it. It would be useful to know whether downstream authors can add this information separately, though.
