### ISSUE TITLE
`ws.close()` waits indefinitely

### ISSUE THREAD

**Issue by lpinca** [faye/faye-websocket-node#58]
This is more a question than an issue.

Currently when calling `ws.close()` the server sends a close frame to the client and waits until the client sends back a close frame.
If the client doesn't send a close frame and the TCP connection is not closed the `ws` object is kept alive indefinitely despite having called `close()` on it.

This example shows the issue.

```js
'use strict';

const WebSocket = require('faye-websocket');
const assert = require('assert');
const http = require('http');
const net = require('net');

const server = http.createServer();

server.on('upgrade', (req, socket, head) => {
  const ws = new WebSocket(req, socket, head);

  ws.on('message', (evt) => {
    assert.strictEqual(evt.data, '');
    console.log('sending close frame');
    ws.close();
  });
  ws.on('close', (evt) => console.log('close', evt.code, evt.reason));
});

server.listen(3000, () => {
  const socket = net.connect(3000, () => {
    let handshake = false;

    socket.write([
      'GET / HTTP/1.1',
      'Upgrade: websocket',
      'Connection: Upgrade',
      'Sec-WebSocket-Key: rfeGe1izPRq2JyonWunAQw==',
      'Sec-WebSocket-Version: 13',
      '',
      ''
    ].join('\r\n'));

    socket.on('data', (data) => {
      if (!handshake) {
        assert.ok(data.equals(Buffer.from([
          'HTTP/1.1 101 Switching Protocols',
          'Upgrade: websocket',
          'Connection: Upgrade',
          'Sec-WebSocket-Accept: prdBmM6el7NzNgJBcdmWum5mTZc=',
          '',
          ''
        ].join('\r\n'))));

        handshake = true;

        //
        // Send a text frame.
        //
        socket.write(Buffer.from([0x81, 0x80, 0x00, 0x00, 0x00, 0x00]));
        return;
      }

      console.log('received close frame');

      //
      // This is the close frame.
      //
      assert.ok(data.equals(Buffer.from([0x88, 0x02, 0x03, 0xe8])));
    });
  });
});
```

The `close` event is never emitted.

I understand this is an edge case and that the client isn't working as expected but is there a clean way to close the connection in such cases?
I can only think of using a timer and destroy the socket when it expires:

```js
const timer = setTimeout(() => ws._stream.destroy(), 15000);
```

but that seems hacky.

**Comment by jcoglan** [comment]
You're right, this is a problem. Your socket should not stay open indefinitely just because the other peer fails to work properly.

I've just pushed https://github.com/faye/faye-websocket-node/commit/560a78b18f2fad7233d91c4a824ced0746a594de, which adds a timeout to shut down the connection 30 seconds after you call `close()`. If the socket has already been closed, this should be a no-op.

Can you test it and let me know if it works? It seems fine on the test case you gave me.

**Comment by lpinca** [comment]
@jcoglan thanks.
It works when `allowHalfOpen` is set to `false` (default value), but it doesn't when it is `true`:

```js
const socket = net.connect({
  allowHalfOpen: true,
  port: 3000
}, () => {});
```

Also I think that the timer should be cleared when `_finalizeClose()` is called otherwise it prevents the whole websocket object from being GC'ed for the whole duration of the timer even when the close procedure works as intended.

**Comment by jcoglan** [comment]
Do you know how to solve the half-open problem? I'm not too familiar with how that works.

**Comment by jcoglan** [comment]
Thanks for the advice. I just pushed a couple more commits that I believe should fix the points you brought up -- could you check them out and let me know what you think?

**Comment by lpinca** [comment]
It should work but I think the closing procedure is slightly different now.
Previously it worked like this:

```
+--------------------+
|     ws.close()     |
+--------------------+
           |           +-------------+
           +---------->| close frame |------------+
                       +-------------+            v
                                       +--------------------+
                                       |  ws._beginClose()  |
                                       +--------------------+
                   +---------------------+        |
           +-------|close frame + TCP FIN|<-------+
           v       +---------------------+
+--------------------+
|  ws._beginClose()  |
|ws._finalizeClose() |
+--------------------+
           |              +-------+
           +------------->|TCP FIN|---------------+
                          +-------+               v
                                       +--------------------+
                                       |ws._finalizeClose() |
                                       +--------------------+
```

Now I think that when `_beginClose()` is called, `_finalizeClose()` is also called as [`this._stream.destroy()`](https://github.com/faye/faye-websocket-node/blob/f3749cd3470e54155a68febe771f3433b50751d0/lib/faye/websocket/api.js#L167) makes the socket no longer readable:

```
+--------------------+
|     ws.close()     |
+--------------------+
           |           +-------------+
           +---------->| close frame |------------+
                       +-------------+            v
                                       +--------------------+
                                       |  ws._beginClose()  |
                                       |ws._finalizeClose() |
                                       +--------------------+
                       +-------------+            |
           +-----------| close frame |<-----------+
           v           +-------------+
+--------------------+
|  ws._beginClose()  |
|ws._finalizeClose() |
+--------------------+
```

I think this is ok but I'm not sure.

**Comment by jcoglan** [comment]
Yeah there's probably some redundancy in that procedure, but historically this has been one of the more brittle areas of the API so I try to make the smallest possible changes to it. I'd rather get this out in the wild and respond to any problems that come up rather than pre-emptively change it even further.

The way I see it, it's fine for those method to be a bit redundant as long as they check the state correctly on entry and only carry out their effects under the right circumstances.

About to release this as 0.11.1.
