### ISSUE TITLE
EventSource compression

### ISSUE THREAD

**Issue by janober** [faye/faye-websocket-node#60]
Hi,
I was wondering if it is somehow possible to compress the messages which get send via EventSource? Did not find any information about that here and the little I found about that topic on other pages I could not get working. Thanks!

**Comment by jcoglan** [comment]
We currently don't support this feature, indeed I didn't realise it was possible. How does it work? Do you just apply chunked-encoding to the entire response stream, or is there some in-protocol compression format supported by EventSource?

**Comment by jcoglan** [comment]
@janober Just checking in, do you have any follow-up response to my above question?

**Comment by jcoglan** [comment]
As there's been no response to my last comment, I'm closing this issue. But do please re-open or file a new issue if this is still a problem.
