### ISSUE TITLE
How to set connetion.binaryType on socket connection?

### ISSUE THREAD

**Issue by Arkine** [faye/faye-websocket-node#61]
Server doesn't recognize type of `connection.binaryType = "arraybuffer";`. 

I am trying to implement a method similar to using the browser webSocket API to set the binaryType but this doesn't seem to work.

**Comment by jcoglan** [comment]
`binaryType` isn't supported by this library. All binary messages are represented using Node's `Buffer` class.

**Comment by Arkine** [comment]
Thank you!
