### ISSUE TITLE
Using with react native

### ISSUE THREAD

**Issue by razerduy** [faye/faye-websocket-node#63]
Can I use this lib inside react native app?

**Comment by jcoglan** [comment]
No, this library is only intended for use with Node.js.

**Comment by dbuarque** [comment]
I see the firebase use faye-websocket on it's js lib, how could we maket it work on react-native as a client?

**Comment by jcoglan** [comment]
I don't know much about Firebase but it looks as though it only uses faye-websocket in its node-specific modules. If you bundle it using Webpack then faye-websocket is not included; I would assume they just use the browser's WebSocket API.

**Comment by Maksims** [comment]
Technically you do not need to use this library on the client if client platform has implementation of WebSocket from W3C (pretty much all browsers do today). As faye-websocket is just a back-end implementation of a spec - it does not require any special library on the client.

**Comment by jcoglan** [comment]
Can I close this issue?

**Comment by razerduy** [comment]
yes
