### ISSUE TITLE
Close timer prevents process from exiting

### ISSUE THREAD

**Issue by lpinca** [faye/faye-websocket-node#64]
Calling [`API#close()`](https://github.com/faye/faye-websocket-node/blob/b85f22e43b4d5baad510c8b3954ec2e94280125a/lib/faye/websocket/api.js#L97-L114) from a listener of the `'error'` event triggers a race condition that prevents the close timer from being cleared.

Here is a test case that tries to connect to a non existing server.

```js
const WebSocket = require('./lib/faye/websocket');

const ws = new WebSocket.Client('ws://localhost:1337');

ws.on('error', function () {
  ws.close();
});
```

The process exits only after 30 sec.

The problem is that [`this._driver.close(reason, code)`](https://github.com/faye/faye-websocket-node/blob/b85f22e43b4d5baad510c8b3954ec2e94280125a/lib/faye/websocket/api.js#L107) causes [API#_finalizeClose()](https://github.com/faye/faye-websocket-node/blob/b85f22e43b4d5baad510c8b3954ec2e94280125a/lib/faye/websocket/api.js#L172-L189) to be called on the same tick and the close timer is set after that.

I'm not sure how to fix this. I can only think of adding a `readyState` check after [`this._driver.close(reason, code)`](https://github.com/faye/faye-websocket-node/blob/b85f22e43b4d5baad510c8b3954ec2e94280125a/lib/faye/websocket/api.js#L107) or run this [instruction](https://github.com/faye/faye-websocket-node/blob/b85f22e43b4d5baad510c8b3954ec2e94280125a/lib/faye/websocket/api.js#L176) unconditionally as the first instruction in the function body.

**Comment by jcoglan** [comment]
This is fixed by #65 -- thanks for reporting :)
