### ISSUE TITLE
bufferedAmount is never updated?

### ISSUE THREAD

**Issue by jpambrun** [faye/faye-websocket-node#66]
It seems that bufferedAmount is never updated, it there any way to know the state of the write buffer? I have poked around substantially, but cannot figure out how to get that information. Any help would be greatly appreciated..

**Comment by jcoglan** [comment]
No, it's not updated. This property only exists so that this library is interface-compatible with the standard WebSocket interface. But since this library is not in control of how the data is buffered and sent over the network (that is handled by node.js), this field is not actually updated.

**Comment by jcoglan** [comment]
@jpambrun is this an ongoing problem for you? Can I close this issue?
