### ISSUE TITLE
Closing with codes other than 1000

### ISSUE THREAD

**Issue by ocbrewing** [faye/faye-websocket-node#67]
I'm curious why codes other than 1000 (or custom codes between 3000-4999) are blocked from close?
We have a sockjs server that does some token authentication.  If the token is invalid we close with code 1008.  We're attempting to update from an old version and this behavior no longer works.

**Comment by jcoglan** [comment]
Applications are only allowed to use the closing codes 1000 and 3000-4999; other codes are reserved for use by the protocol itself. This library aims for compatibility with the browser implementation of the WebSocket API.

This is specified here: https://html.spec.whatwg.org/multipage/web-sockets.html#network

**Comment by ocbrewing** [comment]
thanks, I'd read the spec but just found that it frustrating that it worked before moving to the newer version.  It's also a bit weird   I think we ended up changing out the return code to something 3000+ to get around the issue and making sure our downstream logic was able to handle that.
