### ISSUE TITLE
Add a LICENSE file please

### ISSUE THREAD

**Issue by coopr** [faye/faye-websocket-node#68]
and thanks!

**Comment by arnaud16571542** [comment]
Hello,
I'm using license-checker to get and respect open source license for my commercial software. License-checker generate a json file read by my software. The json file containt all information to display all required information (author, software name, copyright, mandatory licence). 
license-checker use information from npm, and also, extract the licence information from a license file (like LICENSE, LICENSE.md)... For faye-websocket-node, extracted information is coming from README.md..so, it is not good :).
So a dedicated LICENSE for this project is very welcome, thanks !

**Comment by jcoglan** [comment]
This is fixed by #72. For the record, the next release of this library and all other packages in the Faye project will be under the Apache 2.0 license, and the filename will be changed to `LICENSE.md`. I am standardising this across all our repos at the moment.
