### ISSUE TITLE
Several tests are not passing

### ISSUE THREAD

**Issue by braydonf** [faye/faye-websocket-node#69]
**Versions**
faye-websocket master branch (b85f22e43b4d5baad510c8b3954ec2e94280125a)
nodejs v8.11.2

**Expected**
All tests to pass.

**Actual**
Many tests are not passing, see full details at [faye.txt](https://github.com/faye/faye-websocket-node/files/2229744/faye.txt)

**Reproduce**
```
npm install
npm run test
```

I've also include the package-lock.json file that has been used, see [package-lock.json.txt](https://github.com/faye/faye-websocket-node/files/2229761/package-lock.json.txt)

**Comment by braydonf** [comment]
Tests still not passing after using all the same versions as used in the CI run at https://travis-ci.org/faye/faye-websocket-node/jobs/283248608

```
$ node -v
v8.6.0
$ npm ls
faye-websocket@0.11.1 /home/bgf/code/faye/faye-websocket-node
├── http-parser-js@0.4.9
├─┬ jstest@1.0.5
│ └─┬ nopt@4.0.1
│   ├── abbrev@1.1.1
│   └── osenv@0.1.4 deduped
├─┬ osenv@0.1.4
│ ├── os-homedir@1.0.2
│ └── os-tmpdir@1.0.2
├─┬ pace@0.0.4
│ └── charm@0.1.2
├── permessage-deflate@0.1.6
├─┬ websocket-driver@0.7.0
│ ├── http-parser-js@0.4.9 deduped
│ └── websocket-extensions@0.1.2 deduped
└── websocket-extensions@0.1.2
```
[package-lock.json.txt](https://github.com/faye/faye-websocket-node/files/2229792/package-lock.json.txt)

**Comment by braydonf** [comment]
Also tested on Ubuntu 16.04 and 18.04, with tests not passing on both.

**Comment by braydonf** [comment]
Can we get another run of Travis CI to see if it's not passing there?

**Comment by braydonf** [comment]
Realized I could open a PR to trigger a CI build, and indeed the tests are not passing there either, see: https://travis-ci.org/faye/faye-websocket-node/builds/408287982

**Comment by jcoglan** [comment]
The problem seems to be that the self-signed SSL certificates used by the test suite have expired. I've just pushed new ones.
