### ISSUE TITLE
about reconnection

### ISSUE THREAD

**Issue by n9t** [faye/faye-websocket-node#71]
maybe reconnection function is needed

**Comment by jcoglan** [comment]
Could you provide more detail on the problem you're trying to solve? The standard WebSocket API does not provide automatic reconnection and neither does this library, as it usually requires application-level logic depending on the protocol you're using on top of WebSocket.

**Comment by jcoglan** [comment]
@n9t Do you have any follow-up to my question above, or should I close this issue?
