### ISSUE TITLE
Cannot install faye-websocket NOW!!!!

### ISSUE THREAD

**Issue by mienhuang** [faye/faye-websocket-node#81]
when i try install firebase
![image](https://user-images.githubusercontent.com/13617515/123747376-6e9faa00-d8e5-11eb-8d09-b09d47fbe700.png)

when i try manual install
![image](https://user-images.githubusercontent.com/13617515/123747308-5891e980-d8e5-11eb-944c-50a891d5cb3c.png)

specify version

![image](https://user-images.githubusercontent.com/13617515/123747522-a4dd2980-d8e5-11eb-98cd-9a53e8b9d007.png)

Guess something wrong about the package you publish to the npm.

Pleas help fix.

**Comment by jcoglan** [comment]
What have you tried to find out why those packages are not installing?

**Comment by mienhuang** [comment]
what do you mean what have i tried?  
at the beginning i just try to install firebase, but failed, because there is no match version of faye-websocket@0.11.3.

so i checked this package, and tried manual install. still the same error?

did you tried install your package?

**Comment by jcoglan** [comment]
Both the versions you mention above are listed on https://www.npmjs.com/package/faye-websocket and have been installed millions of times in the past week, so they definitely exist.

By my question I meant what have you tried to figure out why they're not installing into your project. Have you tried running different node.js or npm versions? Have you tried installing into an empty directory? Have you found out whether your other dependencies are pinning the version of this package? Have you tried to find out whether anything else in your environment could be causing npm to refuse to install these packages?

**Comment by mienhuang** [comment]
OK, my bad seems like something wrong with my environment.
