### ISSUE TITLE
How do I get the client id as the client.

### ISSUE THREAD

**Issue by axi92** [faye/faye-websocket-node#83]
I dont  have access to the server but I need  the client ID is that possible?

**Comment by jcoglan** [comment]
What problem are you trying to solve and what do you want to use the client ID for?

**Comment by jcoglan** [comment]
Also can I just check what library/package you're asking this question about? I assumed you were talking about https://github.com/faye/faye because you mentioned client IDs; WebSocket connections themselves do not have IDs.

**Comment by Maksims** [comment]
It is up to application developer to implement ID systems and sync up the client with it.

**Comment by axi92** [comment]
Ty all. I was not aware that at the start the initial connection is via post and the handshake. There I got the Id and was able to make a connection.
