### ISSUE TITLE
What is the meaning of the return value of the send function in api.js?

### ISSUE THREAD

**Issue by trhao99** [faye/faye-websocket-node#84]
I am a nodejs novice. When I was looking at the faye-websocket code, I had a question about what is the meaning of the return value of the send function in api.js. Can I use this value to deal with the backpressure problem generated in the process of sending messages?Is there any difference between this return value and this._driver.messages._paused?
![image](https://github.com/faye/faye-websocket-node/assets/43237288/853b7c45-e8df-4de3-bdfa-6271acfecb7e)

**Comment by jcoglan** [comment]
That return value is there to _support_ Node's own back-pressure handling when you glue streams together using the `pipe()` method. You shouldn't use this return value directly or re-implement back-pressure handling yourself.

**Comment by trhao99** [comment]
@jcoglan thank you. I've learned a lot.
I will close this issue.
